// CinematicCameraController — One-Tap TikTok Gameplay Exporter (Session #179).
// Builds 3 Roblox scripts that bundle into every generated game so any player can
// toggle a 9:16 letterboxed cinematic recording mode. Captures rely on OS-level
// screen recording (iOS Control Center / Android Quick Settings / Win+G); this
// module just frames the gameplay and exposes a REC HUD with onboarding.
//
// Wired into apps/functions/src/gameTemplates.ts:9764 via withCinematicCamera().

import type { MultiScriptResult } from './gameTemplates.js';

export interface CinematicCameraOptions {
  /** Default-on letterbox? false → user must press F1 / mobile button to enable. */
  enableByDefault?: boolean;
  /** Color of letterbox bars (default black). */
  letterboxColor?: { r: number; g: number; b: number };
  /** Toggle hotkey on desktop (default F1). */
  hotkey?: 'F1' | 'F2' | 'F3' | 'F4';
}

type AdditionalScript = MultiScriptResult['additionalScripts'][number];

const CONFIG_MODULE_NAME = 'CinematicConfig';
const CONTROLLER_SCRIPT_NAME = 'CinematicCameraController';
const HUD_SCRIPT_NAME = 'CinematicHud';

function buildConfigSource(opts: Required<CinematicCameraOptions>): string {
  const { letterboxColor, enableByDefault, hotkey } = opts;
  return `-- CinematicConfig — generated by cinematicCamera.ts (Session #179)
-- Shared config for CinematicCameraController + CinematicHud LocalScripts.
local Config = {}

Config.EnabledByDefault = ${enableByDefault ? 'true' : 'false'}
Config.LetterboxColor = Color3.fromRGB(${letterboxColor.r}, ${letterboxColor.g}, ${letterboxColor.b})
Config.LetterboxRatio = 9 / 16
-- Session #179 hotfix: F1 is unreliable in Roblox Studio (caught by Studio
-- shortcuts before LocalScript sees it). G is free and matches Roblox FPS
-- conventions. Both keys are accepted at runtime.
Config.HotkeyDesktop = Enum.KeyCode.G
Config.HotkeyDesktopAlt = Enum.KeyCode.${hotkey}
Config.FOVDefault = 70
Config.FOVCinematic = 55
Config.FOVPulseAmount = 18
Config.SlowMoTimeScale = 0.45
Config.OnboardingShown = false
Config.SafeAreaBottomFraction = 0.20

-- Shot presets: relative camera offset from character HumanoidRootPart.
-- Used by CinematicCameraController:setShot(name).
Config.ShotPresets = {
        follow = {
                offset = Vector3.new(0, 4, 12),
                lookAtOffset = Vector3.new(0, 2, 0),
                fov = 55,
                lerpAlpha = 0.10,
        },
        orbit = {
                offset = Vector3.new(10, 5, 10),
                lookAtOffset = Vector3.new(0, 2, 0),
                fov = 60,
                lerpAlpha = 0.06,
                orbitSpeed = 0.4,
        },
        hero = {
                offset = Vector3.new(0, 1.2, 8),
                lookAtOffset = Vector3.new(0, 3, 0),
                fov = 48,
                lerpAlpha = 0.08,
        },
        dolly = {
                offset = Vector3.new(6, 2, 14),
                lookAtOffset = Vector3.new(0, 2, 0),
                fov = 52,
                lerpAlpha = 0.05,
                dollySpeed = 1.5,
        },
        slowmo = {
                offset = Vector3.new(4, 3, 9),
                lookAtOffset = Vector3.new(0, 2, 0),
                fov = 50,
                lerpAlpha = 0.12,
                timeScale = Config.SlowMoTimeScale,
        },
}

Config.ShotOrder = { 'follow', 'orbit', 'hero', 'dolly', 'slowmo' }

return Config
`;
}

function buildControllerSource(): string {
  // Lua source uses ${...} interpolation only via a tagged template later; here it
  // is a pure string so no template-literal escapes needed beyond ordinary backticks.
  return `-- CinematicCameraController.client — generated by cinematicCamera.ts (Session #179)
-- 9:16 letterbox + cinematic shot presets + REC mode.
-- Toggle: F1 (desktop) or floating mobile button (touch). One-Tap UGC capture.

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local StarterGui = game:GetService("StarterGui")
local TweenService = game:GetService("TweenService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local localPlayer = Players.LocalPlayer
local Config = require(ReplicatedStorage:WaitForChild("CinematicConfig"))

local cinematicMode = Config.EnabledByDefault
local activeShotName = "follow"
local orbitAngle = 0
local dollyTime = 0
local lastCFrame = nil

local function getCamera()
        return workspace.CurrentCamera
end

-- Letterbox ScreenGui: two black frames anchored top + bottom (or sides on
-- iPad-landscape). Auto-resizes via UIAspectRatioConstraint listening to
-- viewport.
local letterboxGui = Instance.new("ScreenGui")
letterboxGui.Name = "CinematicLetterbox"
letterboxGui.IgnoreGuiInset = true
letterboxGui.ResetOnSpawn = false
letterboxGui.DisplayOrder = 9999
letterboxGui.Enabled = false
letterboxGui.Parent = localPlayer:WaitForChild("PlayerGui")

local barTop = Instance.new("Frame")
barTop.Name = "BarTop"
barTop.BackgroundColor3 = Config.LetterboxColor
barTop.BorderSizePixel = 0
barTop.AnchorPoint = Vector2.new(0.5, 0)
barTop.Position = UDim2.new(0.5, 0, 0, 0)
barTop.Parent = letterboxGui

local barBottom = barTop:Clone()
barBottom.Name = "BarBottom"
barBottom.AnchorPoint = Vector2.new(0.5, 1)
barBottom.Position = UDim2.new(0.5, 0, 1, 0)
barBottom.Parent = letterboxGui

local barLeft = Instance.new("Frame")
barLeft.Name = "BarLeft"
barLeft.BackgroundColor3 = Config.LetterboxColor
barLeft.BorderSizePixel = 0
barLeft.AnchorPoint = Vector2.new(0, 0.5)
barLeft.Position = UDim2.new(0, 0, 0.5, 0)
barLeft.Parent = letterboxGui

local barRight = barLeft:Clone()
barRight.Name = "BarRight"
barRight.AnchorPoint = Vector2.new(1, 0.5)
barRight.Position = UDim2.new(1, 0, 0.5, 0)
barRight.Parent = letterboxGui

-- Compute letterbox geometry: clamp visible area to 9:16 inside actual viewport.
-- If viewport is wider than 9:16 (landscape phone, desktop) → pillarbox (left+right bars).
-- If viewport is taller than 9:16 (already portrait phone) → letterbox (top+bottom bars).
local function updateLetterbox()
        local cam = getCamera()
        if not cam then return end
        local size = cam.ViewportSize
        local viewportRatio = size.X / math.max(1, size.Y)
        local targetRatio = Config.LetterboxRatio -- 9/16 = 0.5625

        if viewportRatio > targetRatio then
                -- Pillarbox.
                local visibleWidth = size.Y * targetRatio
                local barWidth = math.max(0, (size.X - visibleWidth) / 2)
                barLeft.Size = UDim2.new(0, barWidth, 1, 0)
                barRight.Size = UDim2.new(0, barWidth, 1, 0)
                barTop.Size = UDim2.new(1, 0, 0, 0)
                barBottom.Size = UDim2.new(1, 0, 0, 0)
        else
                -- Letterbox.
                local visibleHeight = size.X / targetRatio
                local barHeight = math.max(0, (size.Y - visibleHeight) / 2)
                barTop.Size = UDim2.new(1, 0, 0, barHeight)
                barBottom.Size = UDim2.new(1, 0, 0, barHeight)
                barLeft.Size = UDim2.new(0, 0, 1, 0)
                barRight.Size = UDim2.new(0, 0, 1, 0)
        end
end

-- Hide / restore default Roblox UI (PlayerList, Chat, Backpack, EmotesMenu).
-- Keep Health visible — players still need feedback.
local hiddenCoreGuiTypes = {
        Enum.CoreGuiType.PlayerList,
        Enum.CoreGuiType.Backpack,
        Enum.CoreGuiType.Chat,
        Enum.CoreGuiType.EmotesMenu,
}
local function setCoreGuiVisible(visible)
        for _, t in ipairs(hiddenCoreGuiTypes) do
                pcall(function()
                        StarterGui:SetCoreGuiEnabled(t, visible)
                end)
        end
end

local function getRoot()
        local char = localPlayer.Character
        if not char then return nil end
        local hrp = char:FindFirstChild("HumanoidRootPart")
        return hrp
end

-- Smoothly drive camera each frame while in cinematic mode.
local function applyShot(dt)
        local hrp = getRoot()
        if not hrp then return end
        local preset = Config.ShotPresets[activeShotName] or Config.ShotPresets.follow
        local cam = getCamera()
        if not cam then return end

        local rootCF = hrp.CFrame
        local offset = preset.offset

        if activeShotName == "orbit" then
                orbitAngle = orbitAngle + dt * (preset.orbitSpeed or 0.4)
                local r = math.sqrt(offset.X * offset.X + offset.Z * offset.Z)
                offset = Vector3.new(math.cos(orbitAngle) * r, offset.Y, math.sin(orbitAngle) * r)
        elseif activeShotName == "dolly" then
                dollyTime = dollyTime + dt * (preset.dollySpeed or 1.5)
                local push = math.sin(dollyTime) * 4
                offset = offset + Vector3.new(0, 0, push)
        end

        local targetPos = rootCF.Position + Vector3.new(offset.X, offset.Y, offset.Z)
        local lookTarget = rootCF.Position + (preset.lookAtOffset or Vector3.new(0, 2, 0))
        local targetCF = CFrame.lookAt(targetPos, lookTarget)

        local alpha = math.clamp(preset.lerpAlpha or 0.1, 0.01, 1)
        if lastCFrame then
                cam.CFrame = lastCFrame:Lerp(targetCF, alpha)
        else
                cam.CFrame = targetCF
        end
        lastCFrame = cam.CFrame

        local targetFOV = preset.fov or Config.FOVCinematic
        cam.FieldOfView = cam.FieldOfView + (targetFOV - cam.FieldOfView) * alpha
end

local renderConn
local function startCinematicLoop()
        if renderConn then return end
        local cam = getCamera()
        if cam then
                cam.CameraType = Enum.CameraType.Scriptable
        end
        renderConn = RunService.RenderStepped:Connect(function(dt)
                applyShot(dt)
        end)
end

local function stopCinematicLoop()
        if renderConn then
                renderConn:Disconnect()
                renderConn = nil
        end
        local cam = getCamera()
        if cam then
                cam.CameraType = Enum.CameraType.Custom
                cam.FieldOfView = Config.FOVDefault
        end
        lastCFrame = nil
end

local function setCinematicMode(enabled)
        cinematicMode = enabled
        letterboxGui.Enabled = enabled
        setCoreGuiVisible(not enabled)
        if enabled then
                updateLetterbox()
                startCinematicLoop()
        else
                stopCinematicLoop()
        end
        -- Broadcast attribute so CinematicHud + other listeners can react.
        localPlayer:SetAttribute("CinematicMode", enabled)
end

local function cycleShot()
        local order = Config.ShotOrder
        for i, name in ipairs(order) do
                if name == activeShotName then
                        activeShotName = order[(i % #order) + 1]
                        localPlayer:SetAttribute("CinematicShot", activeShotName)
                        return
                end
        end
        activeShotName = order[1]
        localPlayer:SetAttribute("CinematicShot", activeShotName)
end

-- Public API published as attributes so HUD and game scripts can pulseFOV on
-- gameplay events (combat hits, level-ups) without coupling to this module.
function _G.CinematicPulseFOV(amount)
        local cam = getCamera()
        if not cam then return end
        local base = cinematicMode and Config.FOVCinematic or Config.FOVDefault
        local punch = amount or Config.FOVPulseAmount
        local punchTween = TweenService:Create(
                cam,
                TweenInfo.new(0.08, Enum.EasingStyle.Quad, Enum.EasingDirection.Out),
                { FieldOfView = base + punch }
        )
        local restoreTween = TweenService:Create(
                cam,
                TweenInfo.new(0.35, Enum.EasingStyle.Quad, Enum.EasingDirection.InOut),
                { FieldOfView = base }
        )
        punchTween:Play()
        punchTween.Completed:Connect(function() restoreTween:Play() end)
end

function _G.CinematicSetMode(enabled)
        setCinematicMode(enabled and true or false)
end

function _G.CinematicCycleShot()
        cycleShot()
end

-- Input bindings — accepts both Hotkey (G) and HotkeyAlt (F1) so users on any
-- platform / launcher overlay (Studio test mode often eats F1) can still toggle.
UserInputService.InputBegan:Connect(function(input, processed)
        if processed then return end
        if input.KeyCode == Config.HotkeyDesktop or input.KeyCode == Config.HotkeyDesktopAlt then
                print("[Cinematic] hotkey toggle:", input.KeyCode.Name)
                setCinematicMode(not cinematicMode)
        elseif cinematicMode and input.KeyCode == Enum.KeyCode.Tab then
                cycleShot()
        end
end)

-- Floating buttons — visible on ALL platforms (desktop, mobile, console).
-- Previously gated to TouchEnabled-only which hid the button in Studio + Mac
-- builds, leaving F1 as the only entry point. Now both work everywhere.
do
        local toggleGui = Instance.new("ScreenGui")
        toggleGui.Name = "CinematicToggleButtons"
        toggleGui.ResetOnSpawn = false
        toggleGui.DisplayOrder = 10000
        toggleGui.Parent = localPlayer:WaitForChild("PlayerGui")

        local btn = Instance.new("TextButton")
        btn.Size = UDim2.fromOffset(64, 64)
        btn.AnchorPoint = Vector2.new(1, 1)
        btn.Position = UDim2.new(1, -16, 1, -120)
        btn.BackgroundColor3 = Color3.fromRGB(20, 20, 28)
        btn.BackgroundTransparency = 0.25
        btn.AutoButtonColor = false
        btn.Text = "🎬"
        btn.TextScaled = true
        btn.TextColor3 = Color3.fromRGB(255, 255, 255)
        btn.Font = Enum.Font.GothamBold
        btn.Parent = toggleGui
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(1, 0)
        corner.Parent = btn
        local stroke = Instance.new("UIStroke")
        stroke.Thickness = 2
        stroke.Color = Color3.fromRGB(255, 80, 110)
        stroke.Parent = btn

        btn.Activated:Connect(function()
                print("[Cinematic] button toggle")
                setCinematicMode(not cinematicMode)
        end)

        local cycleBtn = btn:Clone()
        cycleBtn.Position = UDim2.new(1, -16, 1, -200)
        cycleBtn.Text = "🔄"
        cycleBtn.Parent = toggleGui
        cycleBtn.Activated:Connect(function()
                if cinematicMode then cycleShot() end
        end)
end

-- Listen for viewport resize so letterbox stays correct on rotate / resize.
local cam0 = getCamera()
if cam0 then
        cam0:GetPropertyChangedSignal("ViewportSize"):Connect(function()
                if cinematicMode then updateLetterbox() end
        end)
end

if Config.EnabledByDefault then
        setCinematicMode(true)
end

print("[CinematicCameraController] ready — press " .. Config.HotkeyDesktop.Name .. " / " .. Config.HotkeyDesktopAlt.Name .. " or tap 🎬 (bottom-right) to record cinematic clips")
`;
}

function buildHudSource(): string {
  return `-- CinematicHud.client — generated by cinematicCamera.ts (Session #179)
-- REC indicator + first-time onboarding toast. Listens to LocalPlayer attribute
-- "CinematicMode" set by CinematicCameraController.

local Players = game:GetService("Players")
local StarterGui = game:GetService("StarterGui")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Config = require(ReplicatedStorage:WaitForChild("CinematicConfig"))
local localPlayer = Players.LocalPlayer
local playerGui = localPlayer:WaitForChild("PlayerGui")

local hudGui = Instance.new("ScreenGui")
hudGui.Name = "CinematicHud"
hudGui.ResetOnSpawn = false
hudGui.IgnoreGuiInset = true
hudGui.DisplayOrder = 10001
hudGui.Enabled = false
hudGui.Parent = playerGui

-- REC pill: red dot + "REC" + active shot name + share-link hint.
local pill = Instance.new("Frame")
pill.Size = UDim2.fromOffset(180, 36)
pill.AnchorPoint = Vector2.new(1, 0)
pill.Position = UDim2.new(1, -24, 0, 60)
pill.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
pill.BackgroundTransparency = 0.35
pill.BorderSizePixel = 0
pill.Parent = hudGui
local pillCorner = Instance.new("UICorner")
pillCorner.CornerRadius = UDim.new(0.5, 0)
pillCorner.Parent = pill

local dot = Instance.new("Frame")
dot.Size = UDim2.fromOffset(12, 12)
dot.Position = UDim2.new(0, 14, 0.5, -6)
dot.BackgroundColor3 = Color3.fromRGB(255, 70, 80)
dot.BorderSizePixel = 0
dot.Parent = pill
local dotCorner = Instance.new("UICorner")
dotCorner.CornerRadius = UDim.new(1, 0)
dotCorner.Parent = dot

local label = Instance.new("TextLabel")
label.Size = UDim2.new(1, -36, 1, 0)
label.Position = UDim2.new(0, 36, 0, 0)
label.BackgroundTransparency = 1
label.Font = Enum.Font.GothamBold
label.TextSize = 14
label.TextXAlignment = Enum.TextXAlignment.Left
label.TextColor3 = Color3.fromRGB(255, 255, 255)
label.Text = "REC · follow"
label.Parent = pill

-- Bottom safe-area caption hint (TikTok safe-area is bottom 20%).
local safeHint = Instance.new("TextLabel")
safeHint.Size = UDim2.new(1, -120, 0, 24)
safeHint.AnchorPoint = Vector2.new(0.5, 1)
safeHint.Position = UDim2.new(0.5, 0, 1, -16)
safeHint.BackgroundTransparency = 1
safeHint.Font = Enum.Font.Gotham
safeHint.TextSize = 12
safeHint.TextColor3 = Color3.fromRGB(255, 255, 255)
safeHint.TextStrokeColor3 = Color3.fromRGB(0, 0, 0)
safeHint.TextStrokeTransparency = 0.4
safeHint.Text = "Swipe down → tap Screen Record · Tab cycles shots"
safeHint.Parent = hudGui

-- Blink the REC dot.
local blinkOn = true
local lastBlink = 0
RunService.Heartbeat:Connect(function(dt)
        if not hudGui.Enabled then return end
        lastBlink = lastBlink + dt
        if lastBlink > 0.55 then
                lastBlink = 0
                blinkOn = not blinkOn
                dot.BackgroundTransparency = blinkOn and 0 or 0.7
        end
end)

-- Onboarding toast (first time only). Uses StarterGui:SetCore in a pcall so the
-- whole HUD doesn't fail if the API is unavailable.
local function showOnboardingToast()
        if Config.OnboardingShown or localPlayer:GetAttribute("CinematicOnboardingShown") then
                return
        end
        localPlayer:SetAttribute("CinematicOnboardingShown", true)
        pcall(function()
                StarterGui:SetCore("SendNotification", {
                        Title = "🎬 Recording mode",
                        Text = "Swipe down → tap Screen Record · post to TikTok via the AI Gold app",
                        Duration = 8,
                })
        end)
end

local function refreshShotLabel()
        local shotName = localPlayer:GetAttribute("CinematicShot") or "follow"
        label.Text = "REC · " .. shotName
end

local function setVisible(enabled)
        hudGui.Enabled = enabled
        if enabled then
                refreshShotLabel()
                showOnboardingToast()
                pill.BackgroundTransparency = 1
                local fade = TweenService:Create(pill, TweenInfo.new(0.25), { BackgroundTransparency = 0.35 })
                fade:Play()
        end
end

localPlayer:GetAttributeChangedSignal("CinematicMode"):Connect(function()
        setVisible(localPlayer:GetAttribute("CinematicMode") == true)
end)
localPlayer:GetAttributeChangedSignal("CinematicShot"):Connect(refreshShotLabel)

-- Sync initial state in case controller already enabled by default.
setVisible(localPlayer:GetAttribute("CinematicMode") == true)

print("[CinematicHud] ready")
`;
}

export function buildCinematicCameraScripts(
  options: CinematicCameraOptions = {},
): AdditionalScript[] {
  const opts: Required<CinematicCameraOptions> = {
    enableByDefault: options.enableByDefault ?? false,
    letterboxColor: options.letterboxColor ?? { r: 0, g: 0, b: 0 },
    hotkey: options.hotkey ?? 'F1',
  };

  return [
    {
      name: CONFIG_MODULE_NAME,
      scriptType: 'ModuleScript',
      container: 'ReplicatedStorage',
      source: buildConfigSource(opts),
    },
    {
      name: CONTROLLER_SCRIPT_NAME,
      scriptType: 'LocalScript',
      container: 'StarterPlayerScripts',
      source: buildControllerSource(),
    },
    {
      name: HUD_SCRIPT_NAME,
      scriptType: 'LocalScript',
      container: 'StarterPlayerScripts',
      source: buildHudSource(),
    },
  ];
}

/** Wraps a builder result with the cinematic camera scripts. Idempotent — if
 *  the controller is already present (e.g. nested calls) it won't double-add. */
export function withCinematicCamera(
  result: string | MultiScriptResult,
  options: CinematicCameraOptions = {},
): MultiScriptResult {
  const base: MultiScriptResult =
    typeof result === 'string'
      ? { serverScript: result, additionalScripts: [] }
      : result;

  const alreadyHas = base.additionalScripts.some(
    (s: AdditionalScript) => s.name === CONTROLLER_SCRIPT_NAME,
  );
  if (alreadyHas) return base;

  return {
    ...base,
    additionalScripts: [
      ...base.additionalScripts,
      ...buildCinematicCameraScripts(options),
    ],
  };
}
