// robloxDecalUpload.ts — Open Cloud Decal upload on behalf of an OAuth user.
// Session 382 Phase 2.
//
// Open Cloud `POST /assets/v1/assets` supports: Animation, Audio, Decal,
// Image, Mesh, Model, Video (as of May 2026). Classic Shirt/Pants/T-Shirt
// are NOT supported via Open Cloud — those still require legacy cookie auth.
// For our Glow-Up Studio, only the face/aura decal is auto-uploaded.
//
// Flow:
//   1. Caller passes firebaseUid + decal PNG buffer + display name.
//   2. We fetch the user's Roblox OAuth token (refreshing if needed) from
//      Firestore via getRobloxUserToken().
//   3. Multipart POST to /assets/v1/assets — { request: JSON, fileContent }.
//   4. Roblox returns { path: "operations/<id>" }; we poll
//      /assets/v1/operations/{id} until done (typically 2–10s).
//   5. Return { assetId, decalAssetUrl }.
//
// Requires OAuth scope `asset:write` — already in our app's scope list.

import { logger } from 'firebase-functions/v2';
import { getRobloxUserToken } from './robloxOAuth.js';

const ASSETS_API = 'https://apis.roblox.com/assets/v1/assets';
const OPERATIONS_API = 'https://apis.roblox.com/assets/v1/operations';

const POLL_INTERVAL_MS = 1_000;
const POLL_TIMEOUT_MS = 30_000;

export class DecalUploadNotConnectedError extends Error {
  constructor() {
    super('User has not connected Roblox via OAuth');
    this.name = 'DecalUploadNotConnectedError';
  }
}

export interface DecalUploadResult {
  assetId: string;
  decalAssetUrl: string;
}

export interface UploadDecalArgs {
  firebaseUid: string;
  pngBuffer: Buffer;
  displayName: string;
  description?: string;
}

export async function uploadDecalForUser(args: UploadDecalArgs): Promise<DecalUploadResult> {
  const token = await getRobloxUserToken(args.firebaseUid);
  if (!token) {
    throw new DecalUploadNotConnectedError();
  }
  const robloxUserId = token.robloxUserId;
  const accessToken = token.accessToken;

  const metadata = {
    assetType: 'Decal',
    displayName: args.displayName.slice(0, 50),
    description: (args.description ?? 'Generated by Kami Gold AI Glow-Up Studio.').slice(0, 1000),
    creationContext: { creator: { userId: String(robloxUserId) } },
  };

  // Multipart manually: Node 18+ has FormData + Blob globally.
  const form = new FormData();
  form.append('request', JSON.stringify(metadata));
  const blob = new Blob([new Uint8Array(args.pngBuffer)], { type: 'image/png' });
  form.append('fileContent', blob, 'decal.png');

  const createResp = await fetch(ASSETS_API, {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${accessToken}` },
    body: form,
    signal: AbortSignal.timeout(20_000),
  });
  if (!createResp.ok) {
    const text = await createResp.text().catch(() => '');
    throw new Error(`Roblox /assets POST failed: HTTP ${createResp.status} — ${text.slice(0, 300)}`);
  }
  const createJson = await createResp.json() as { path?: string; operationId?: string };
  const opPath = createJson.path ?? (createJson.operationId ? `operations/${createJson.operationId}` : null);
  if (!opPath) {
    throw new Error(`Roblox /assets POST returned no operation path: ${JSON.stringify(createJson).slice(0, 300)}`);
  }
  const operationId = opPath.replace(/^operations\//, '');

  // Poll operation until done or timeout.
  const started = Date.now();
  while (Date.now() - started < POLL_TIMEOUT_MS) {
    await new Promise((r) => setTimeout(r, POLL_INTERVAL_MS));
    const pollResp = await fetch(`${OPERATIONS_API}/${encodeURIComponent(operationId)}`, {
      headers: { 'Authorization': `Bearer ${accessToken}` },
      signal: AbortSignal.timeout(8_000),
    });
    if (!pollResp.ok) {
      logger.warn('[robloxDecalUpload] poll non-200', { status: pollResp.status, operationId });
      continue;
    }
    const pollJson = await pollResp.json() as {
      done?: boolean;
      response?: { assetId?: string | number };
      error?: { code?: string; message?: string };
    };
    if (pollJson.done) {
      if (pollJson.error) {
        throw new Error(`Roblox decal operation errored: ${pollJson.error.code ?? '?'} ${pollJson.error.message ?? ''}`);
      }
      const assetId = pollJson.response?.assetId != null ? String(pollJson.response.assetId) : null;
      if (!assetId) {
        throw new Error(`Roblox decal operation done but no assetId returned: ${JSON.stringify(pollJson).slice(0, 300)}`);
      }
      return {
        assetId,
        decalAssetUrl: `https://www.roblox.com/library/${assetId}`,
      };
    }
  }
  throw new Error(`Roblox decal upload timed out after ${POLL_TIMEOUT_MS}ms (operation ${operationId})`);
}
